/*
    File contains all actions types related to user actions
*/

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const RESET_LOADING = 'RESET_LOADING';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';

export const ON_LOGIN_EMAIL_CHANGE = 'ON_LOGIN_EMAIL_CHANGE';
export const ON_LOGIN_PASSWORD_CHANGE = 'ON_LOGIN_PASSWORD_CHANGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ON_SIGNUP_TYPE_CHANGE = 'ON_SIGNUP_TYPE_CHANGE';
export const ON_SIGNUP_NAME_CHANGE = 'ON_SIGNUP_NAME_CHANGE';
export const ON_SIGNUP_MOBILE_CHANGE = 'ON_SIGNUP_MOBILE_CHANGE';
export const ON_SIGNUP_EMAIL_CHANGE = 'ON_SIGNUP_EMAIL_CHANGE';
export const ON_SIGNUP_PASSWORD_CHANGE = 'ON_SIGNUP_PASSWORD_CHANGE';
export const ON_SIGNUP_PRIVACY_CHANGED = 'ON_SIGNUP_PRIVACY_CHANGED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const ON_RESET_EMAIL_CHANGE = 'ON_RESET_EMAIL_CHANGE';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILED = 'RESET_FAILED';